# Dependencies
markdown: kramdown
highlighter: rouge

# Gems
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-seo-tag

# Settings
exclude:
  [
    CNAME,
    README.md,
    LICENSE.md,
    .gitignore,
    package.json,
    yarn.lock,
    _js,
    _scss,
    _images,
    gulpfile.js,
    gulpconfig.js,
    node_modules,
    gemfile,
    Gemfile.lock,
    lint-staged.config.js,
    prettier.config.js,
  ]
permalink: /:title/
compress_html:
  clippings: all
  comments: all

# Site meta
title: 'Fairyland'
tagline: 'Believe in Magic.'
description: 'Welcome to Fairyland! A place full of heroic git commits and mythical code-bugs!'
keywords: 'github, jekyll, fairyĺand'
url: https://burningfairy.github.io
baseurl: ""
assets: /assets
images: /images
image: index.jpg
logo: /assets/icons/apple-icon-144x144.png
dark_theme: false

author:
  name: Burning Fairy
  bio: 
  image: fairy.png
  url:
  email: irina.karner@outlook.at
  twitter:

social:
  twitter:
  instagram:
  github: https://github.com/burningfairy
  medium:

version: 4.0.0

github:
  repo: https://github.com/burningfairy/burningfairy.github.io

# Integrations
# typekit:              fcv7rfe

google_fonts:
  Overpass: 400, 600, 800

google_analytics_key: UA-94021817-2
# google_site_verification: Z-pc_HPc4XNBz8xg1fgtxO2MSIYLirZc2jWTNq0bJyM

# Content
excerpt_separator: <!-- Read more -->

navigation:
  GitHub: https://github.com/burningfairy
